pipeline {
    agent { label "Jenkins-Agent" }
    environment {
              APP_NAME = "register-app-pipeline"
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
               steps {
                   git branch: 'main', credentialsId: 'github', url: 'https://github.com/KAVIRAJec/Devops-Projects'
               }
        }

        stage("Update the Deployment Tags") {
            steps {
                sh """
                   cd Jenkins-K8S-CICD/CD-gitops-register-app
                   cat deployment.yaml
                   sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                   cat deployment.yaml
                """
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                sh """
                   cd Jenkins-K8S-CICD/CD-gitops-register-app
                   git config --global user.name "KAVIRAJec"
                   git config --global user.email "kavirajppm2003@gmail.com"
                   git add deployment.yaml
                   git commit -m "Updated Deployment Manifest"
                """
                withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                  sh "git push https://github.com/KAVIRAJec/Devops-Projects main"
                }
            }
        }
    }
}
