---
- name: start docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    
- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: restart docker containers
  shell: |
    cd /opt/{{ project_name }}/docker/{{ item.name }}
    docker-compose down
    docker-compose up -d
  loop: "{{ docker_apps }}"