# Application settings
app_name: "myapp"
app_version: "1.0.0"
app_user: "myapp_user"
app_group: "myapp_group"

# Database settings
db_name: "myapp_db"
db_user: "user"
db_password: "secret"
db_host: "{{ groups['dbhosts'][0] }}"
db_port: 5432

# Backend settings
backend_port: 8000
backend_dir: "/opt/{{ app_name }}/backend"

# Frontend settings
frontend_port: 80
frontend_dir: "/var/www/{{ app_name }}"

# Common packages
common_packages:
  - git
  - curl
  - wget
  - unzip