---
- name: Create Security Group
  amazon.aws.ec2_security_group:
    name: "{{ security_group_name }}"
    description: "Security group for {{ instance_name }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    tags: "{{ common_tags }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ allowed_cidr_blocks }}"
        rule_desc: "SSH access"
      - proto: tcp
        ports:
          - 80
        cidr_ip: ["0.0.0.0/0"]
        rule_desc: "HTTP access"
      - proto: tcp
        ports:
          - 443
        cidr_ip: ["0.0.0.0/0"]
        rule_desc: "HTTPS access"
      - proto: tcp
        ports:
          - 8080
        cidr_ip: ["0.0.0.0/0"]
        rule_desc: "Application port"
    rules_egress:
      - proto: all
        cidr_ip: "0.0.0.0/0"
        rule_desc: "All outbound traffic"
    state: present
  register: security_group

- name: Create Key Pair
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ aws_region }}"
    state: present
  register: key_pair

- name: Save private key to file
  copy:
    content: "{{ key_pair.key.private_key }}"
    dest: "~/.ssh/{{ key_name }}.pem"
    mode: '0600'
  when: key_pair.key.private_key is defined

- name: Set security group fact
  set_fact:
    security_group_id: "{{ security_group.group_id }}"