---
- name: Launch EC2 Instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ public_subnet_id }}"
    security_groups:
      - "{{ security_group_id }}"
    network:
      assign_public_ip: "{{ assign_public_ip }}"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_size: "{{ volume_size }}"
          volume_type: "{{ volume_type }}"
          delete_on_termination: "{{ delete_on_termination }}"
    user_data: "{{ user_data }}"
    monitoring: "{{ monitoring }}"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ instance_name }}"
      "{{ common_tags | combine(instance_tags | default({})) }}"
    state: present
    wait: true
    wait_timeout: 600
  register: ec2_instance

- name: Wait for instance to be reachable
  wait_for:
    host: "{{ ec2_instance.instances[0].public_ip_address }}"
    port: 22
    delay: 60
    timeout: 600
    state: started
  when: ec2_instance.instances[0].public_ip_address is defined

- name: Add instance to inventory
  add_host:
    name: "{{ instance_name }}"
    ansible_host: "{{ ec2_instance.instances[0].public_ip_address }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_private_key_file: "~/.ssh/{{ key_name }}.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    groups: 
      - aws_instances
      - "{{ environment }}_instances"

- name: Create instance info file
  template:
    src: instance_info.txt.j2
    dest: "./{{ instance_name }}_info.txt"