---
# Environment Configuration
env_name: "prod"
deployment_environment: "production"

instance_type: "t3.medium"
volume_size: 50
volume_type: "gp3"
monitoring: true

# Restrict SSH access (replace with your IP)
allowed_cidr_blocks:
  - "203.0.113.0/24"  # Replace with your office IP
  - "198.51.100.0/24"

instance_tags:
  Environment: "production"
  BackupRequired: "true"
  MonitoringLevel: "enhanced"