---
all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: localhost
          ansible_connection: local
        web2:
          # ansible_host: 192.168.1.101
          # ansible_user: ubuntu
    appservers:
      hosts:
        app1:
          ansible_host: localhost
          ansible_connection: local
    dbservers:
      hosts:
        db1:
          ansible_host: localhost
          ansible_connection: local